{{- if not .Values.externalConfig.secretRef.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-auth.fullname" . }}-config
data:
  config.yml: {{ toYaml .Values.config | b64enc }}
{{- end }}
