apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-auth.fullname" . }}
  labels:
    {{- include "docker-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docker-auth.selectorLabels" . | nindent 4 }}
